spring:
application:
  name: taco-cloud
  thymeleaf:
    cache: false
  data:
    cassandra:
      contact-points: 127.0.0.1  # ????????? ?????????? ????? ??? ???????????
      port: 9042
      keyspace-name: taco_cloud
      schema-action: recreate
      local-datacenter: datacenter1
